services:
  wordpress:
    image: wordpress:latest
    pull_policy: always
    ports:
      - "8000:80"
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_HOME=http://localhost:8000
      - WORDPRESS_SITEURL=http://localhost:8000
      - WORDPRESS_DEBUG=true
    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

  db:
    image: mysql:8
    pull_policy: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    pull_policy: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db

volumes:
  db_data:
